services:
  postgres:
    build: 
      context: .  
      dockerfile: postgresql.Dockerfile 
    container_name: mlpapers-postgres
    restart: unless-stopped 
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    network_mode: host

